# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=10)),
                ('volume', models.CharField(max_length=50, null=True)),
                ('investment_passenger', models.CharField(max_length=50, null=True)),
                ('loan_passenger', models.CharField(max_length=50, null=True)),
                ('average_interest_rate', models.CharField(max_length=50, null=True)),
                ('average_loan_period', models.CharField(max_length=50, null=True)),
                ('loan_bid', models.CharField(max_length=50, null=True)),
                ('registered_capital', models.CharField(max_length=50, null=True)),
                ('time_for_full_bid', models.CharField(max_length=50, null=True)),
                ('accounted_revenue', models.CharField(max_length=50, null=True)),
                ('capital_inflow_in_30_days', models.CharField(max_length=50, null=True)),
                ('volumn_weighted_time', models.CharField(max_length=50, null=True)),
                ('accounted_revenue_in_60_days', models.CharField(max_length=50, null=True)),
                ('proportion_of_top_10_tuhao_accounted_revenue', models.CharField(max_length=50, null=True)),
                ('average_investment_amount', models.CharField(max_length=50, null=True)),
                ('proportion_of_top_10_borrower_accounted_revenue', models.CharField(max_length=50, null=True)),
                ('average_loan_amount', models.CharField(max_length=50, null=True)),
                ('capital_lever', models.CharField(max_length=50, null=True)),
                ('operation_time', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'wangjia_data',
            },
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.CharField(max_length=20, unique=True)),
                ('source', models.URLField(null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('created', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=60, null=True)),
                ('link', models.URLField(null=True)),
                ('reason', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('raw_content', models.TextField(null=True)),
                ('image_url', models.TextField(null=True)),
            ],
            options={
                'db_table': 'wangjia_exposure',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=20, unique=True)),
                ('allPin', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('link', models.URLField(null=True)),
                ('province_id', models.PositiveSmallIntegerField(default=0)),
                ('launch_time', models.CharField(max_length=10, null=True)),
                ('icon_url', models.URLField(null=True)),
            ],
            options={
                'db_table': 'wangjia_navigation',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.CharField(max_length=10)),
                ('category_id', models.PositiveSmallIntegerField(default=0)),
                ('source', models.URLField(null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('created', models.CharField(max_length=20, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('summary', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('raw_content', models.TextField(null=True)),
                ('image_url', models.TextField(null=True)),
            ],
            options={
                'db_table': 'wangjia_news',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'wangjia_news_category',
            },
        ),
        migrations.CreateModel(
            name='PlatformFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('link', models.URLField(null=True)),
                ('feature', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'p2peye_platform_feature',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pin', models.CharField(max_length=20)),
                ('problem_time', models.CharField(max_length=10, null=True)),
                ('launch_time', models.CharField(max_length=10, null=True)),
                ('registered_capital', models.CharField(max_length=50, null=True)),
                ('province_id', models.PositiveSmallIntegerField(default=0)),
                ('accounted_revenue', models.CharField(max_length=50, null=True)),
                ('involved_passenger', models.CharField(max_length=50, null=True)),
                ('event_category', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'wangjia_problem',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=10)),
                ('exponent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('launch_time', models.CharField(max_length=10, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('deal', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('popularity', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('lever', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('brand', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('dispersity', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('mobility', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('transparency', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'wangjia_rating',
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('navigation', models.OneToOneField(db_column=b'id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stalk.Navigation')),
                ('name', models.CharField(max_length=50, null=True)),
                ('link', models.URLField(null=True)),
                ('launch_time', models.CharField(max_length=10, null=True)),
                ('logo_url', models.URLField(null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('introduction', models.TextField(null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('artificial_person', models.CharField(max_length=50, null=True)),
                ('company_type', models.CharField(max_length=50, null=True)),
                ('shareholder_stucture', models.CharField(max_length=500, null=True)),
                ('registered_capital', models.CharField(max_length=50, null=True)),
                ('contributed_capital', models.CharField(max_length=50, null=True)),
                ('registered_address', models.CharField(max_length=100, null=True)),
                ('opening_date', models.CharField(max_length=20, null=True)),
                ('approved_date', models.CharField(max_length=20, null=True)),
                ('registration_authority', models.CharField(max_length=50, null=True)),
                ('business_licence', models.CharField(max_length=50, null=True)),
                ('institutional_framework', models.CharField(max_length=50, null=True)),
                ('tax_registration_num', models.CharField(max_length=50, null=True)),
                ('domain_name', models.CharField(max_length=150, null=True)),
                ('domain_date', models.CharField(max_length=20, null=True)),
                ('domain_company_type', models.CharField(max_length=50, null=True)),
                ('domain_company_name', models.CharField(max_length=50, null=True)),
                ('icp', models.CharField(max_length=50, null=True)),
                ('company_person_avatar_url', models.TextField(null=True)),
                ('company_person', models.TextField(null=True)),
                ('management_fee', models.TextField(null=True)),
                ('prepaid_fee', models.TextField(null=True)),
                ('cash_withdrawal_fee', models.TextField(null=True)),
                ('vip_fee', models.TextField(null=True)),
                ('transfer_fee', models.TextField(null=True)),
                ('mode_of_payment', models.CharField(max_length=50, null=True)),
                ('contact_address', models.CharField(max_length=100, null=True)),
                ('phone_400', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('fax', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('is_automatic_bid', models.CharField(max_length=50, null=True)),
                ('is_equitable_assignment', models.CharField(max_length=50, null=True)),
                ('trust_fund', models.CharField(max_length=100, null=True)),
                ('tender_security', models.CharField(max_length=100, null=True)),
                ('security_mode', models.CharField(max_length=100, null=True)),
                ('guarantee_institution', models.CharField(max_length=300, null=True)),
                ('business_type', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'wangjia_archive',
            },
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('name', 'timestamp')]),
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together=set([('thread', 'category_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together=set([('name', 'timestamp')]),
        ),
    ]
