# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('amount', models.CharField(max_length=20, null=True)),
                ('time', models.CharField(max_length=20, null=True)),
                ('source', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'weidai_bidder',
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('interest_rate', models.CharField(max_length=20, null=True)),
                ('time_limit', models.CharField(max_length=20, null=True)),
                ('launch_date', models.CharField(max_length=20, null=True)),
                ('volume', models.CharField(max_length=20, null=True)),
                ('transfer_amount', models.CharField(max_length=20, null=True)),
                ('progress', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'weidai_tender',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('tender', models.OneToOneField(db_column=b'id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stalk.Tender')),
                ('title', models.CharField(max_length=50, null=True)),
                ('feature', models.CharField(max_length=50, null=True)),
                ('volume', models.CharField(max_length=50, null=True)),
                ('annual_profit', models.CharField(max_length=20)),
                ('time_limit', models.CharField(max_length=20, null=True)),
                ('interest_time', models.CharField(max_length=20, null=True)),
                ('mode_of_payment', models.CharField(max_length=50, null=True)),
                ('launch_time', models.CharField(max_length=10, null=True)),
                ('progress', models.CharField(max_length=20, null=True)),
                ('source_strore', models.CharField(max_length=20, null=True)),
                ('has_security_guarantee', models.PositiveSmallIntegerField(default=0)),
                ('user', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('marital_status', models.CharField(max_length=20, null=True)),
                ('hometown', models.CharField(max_length=50, null=True)),
                ('payoffed', models.CharField(max_length=20, null=True)),
                ('pending', models.CharField(max_length=20, null=True)),
                ('overdue', models.CharField(max_length=20, null=True)),
                ('vehicle_brand', models.CharField(max_length=20, null=True)),
                ('vehicle_number', models.CharField(max_length=20, null=True)),
                ('vehicle_kilometers', models.CharField(max_length=20, null=True)),
                ('vehicle_price', models.CharField(max_length=20, null=True)),
                ('mortgage_value', models.CharField(max_length=20, null=True)),
                ('verification_time', models.CharField(max_length=20, null=True)),
                ('verification_explanation', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'weidai_bid',
            },
        ),
    ]
