# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0004_auto_20160127_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=40)),
                ('project', models.CharField(max_length=20, null=True)),
                ('spider', models.CharField(max_length=20, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('job_id', 'project', 'spider')]),
        ),
    ]
