# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0008_auto_20160505_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest',
            name='invest_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='bid_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='invest',
            unique_together=set([('plat_id', 'invest_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='loan',
            unique_together=set([('plat_id', 'bid_id')]),
        ),
    ]
