# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0009_auto_20160517_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApistoreYiyuanFinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(null=True, unique=True)),
                ('all_list', models.TextField(null=True)),
                ('pub_date', models.CharField(max_length=50, null=True)),
                ('title', models.TextField(null=True)),
                ('channel_name', models.TextField(null=True)),
                ('image_urls', models.TextField(null=True)),
                ('desc', models.TextField(null=True)),
                ('source', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'baidu_apistore_yiyuan_finance',
            },
        ),
    ]
