# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0010_yiyuanfinance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basicdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_id', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20, null=True)),
                ('turnover_amount', models.CharField(max_length=20, null=True)),
                ('trade_amount', models.CharField(max_length=20, null=True)),
                ('borrower_amount', models.CharField(max_length=20, null=True)),
                ('investor_amount', models.CharField(max_length=20, null=True)),
                ('loan_amount_per_capita', models.CharField(max_length=20, null=True)),
                ('avg_loan_per_trade', models.CharField(max_length=20, null=True)),
                ('invest_amount_per_capita', models.CharField(max_length=20, null=True)),
                ('avg_invest_per_trade', models.CharField(max_length=20, null=True)),
                ('loan_balance', models.CharField(max_length=20, null=True)),
                ('max_borrower_ratio', models.CharField(max_length=20, null=True)),
                ('topten_borrowers_ratio', models.CharField(max_length=20, null=True)),
                ('avg_full_time', models.CharField(max_length=20, null=True)),
                ('accum_default_rate', models.CharField(max_length=20, null=True)),
                ('product_overdue_rate', models.CharField(max_length=20, null=True)),
                ('three_month_overdue_rate', models.CharField(max_length=20, null=True)),
                ('overdue_loan_amount', models.CharField(max_length=20, null=True)),
                ('compensatory_amount', models.CharField(max_length=20, null=True)),
                ('loan_overdue_rate', models.CharField(max_length=20, null=True)),
                ('bad_debt_rate', models.CharField(max_length=20, null=True)),
                ('customer_complaints', models.CharField(max_length=20, null=True)),
                ('customer_complaints_solve', models.CharField(max_length=20, null=True)),
                ('interest_rate', models.CharField(max_length=20, null=True)),
                ('avg_borrow_period', models.CharField(max_length=20, null=True)),
                ('topten_investor_ratio', models.CharField(max_length=20, null=True)),
                ('financial_leverage', models.CharField(max_length=20, null=True)),
                ('repaid_amount', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'aif_basicdata',
            },
        ),
        migrations.CreateModel(
            name='Dailydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_id', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20, null=True)),
                ('current_date', models.CharField(max_length=20, null=True)),
                ('daily_turnover', models.CharField(max_length=20, null=True)),
                ('daily_trade_cnt', models.CharField(max_length=20, null=True)),
                ('daily_invest_cnt', models.CharField(max_length=20, null=True)),
                ('thityday_income', models.CharField(max_length=20, null=True)),
                ('service_time', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'aif_dailydata',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailydata',
            unique_together=set([('plat_id', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='basicdata',
            unique_together=set([('plat_id', 'date')]),
        ),
    ]
